backend:
  name: github
  repo: Squigly77/myblog
  branch: master

publish_mode: editorial_workflow

media_folder: "content/images"
public_folder: "../../../images"

collections:
  - label: "Blog"
    name: "blog"
    folder: "content"
    create: true
    slug: "{{slug}}"
    identifier_field: Title
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Publish Date", name: "Date", widget: "date",format: "YYYY-MM-DD"}
      - {label: "Modified", name: "Modified", widget: "string", required: false}
      - {label: "Category", name: "Category", widget: "string"}
      - {label: "Tags", name: "Tags", widget: "string"}
      - {label: "Slug", name: "Slug", widget: "string"}
      - {label: "Related", name: "related_post", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
