backend:
  name: github
  repo: Squigly77/myblog
  branch: master

publish_mode: editorial_workflow

media_folder: "images"
public_folder: "images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Publish Date", name: "Date", widget: "date",format: "YYYY-MM-DD"}
      - {label: "Category", name: "Category", widget: "list"}
      - {label: "Tags", name: "Tags", widget: "list"}
      - {label: "Related", name: "related_post", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}