backend:
  name: git-gateway
  repo: Squigly77/myblog
  branch: master

publish_mode: editorial_workflow

media_folder: "images"
public_folder: "images"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Publish Date", name: "Date", widget: "date",format: "YYYY-MM-DD"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Category", name: "Categories", widget: "list"}
      - {label: "Tags", name: "Tags", widget: "list"}
      - {label: "Related", name: "related_post", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}