backend:
  name: github
  repo: Squigly77/myblog
  branch: master

publish_mode: editorial_workflow

media_folder: "images"
public_folder: "images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content"
    identifier_field: "Title"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "Title", widget: "string"}
      - {label: "Publish Date", name: "Date", widget: "date",format: "YYYY-MM-DD"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Related", name: "related_post", widget: "string", required: false}
      - {label: "Slug", name: "slug", widget: "string"}